language: nodejs
node_js:
- "10.3.0"
before_script:
- yarn
script:
- yarn build
cache:
  directories:
  - "node_modules"
  yarn: true
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: build
